# Generated by Django 4.0.4 on 2022-06-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(default='', max_length=50)),
                ('product_name', models.CharField(default='', max_length=50)),
                ('product_category', models.CharField(default='', max_length=30)),
                ('product_image', models.ImageField(default='', upload_to='home/img')),
                ('product_price', models.CharField(default='', max_length=30)),
                ('product_color1', models.CharField(default='', max_length=30)),
                ('product_color2', models.CharField(default='', max_length=30)),
                ('product_color3', models.CharField(default='', max_length=30)),
                ('product_des', models.CharField(default='', max_length=200)),
                ('product_qty', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
