# Generated by Django 4.0.4 on 2022-05-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=10)),
                ('pro_desc', models.CharField(max_length=50)),
                ('pro_img', models.ImageField(upload_to='home/img')),
            ],
        ),
    ]
