# Generated by Django 4.0.4 on 2022-06-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.ImageField(default='', upload_to='home/img'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_price',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='product_qty',
            field=models.CharField(default='', max_length=200),
        ),
    ]
