# Generated by Django 4.0.4 on 2022-05-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='user_login',
        ),
    ]
