# Generated by Django 4.0.4 on 2022-06-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_first_name_order_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product_qty',
            new_name='qty',
        ),
    ]
