# Generated by Django 4.0.4 on 2022-05-06 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_login',
            new_name='loginUser',
        ),
    ]
