# Generated by Django 4.0.4 on 2022-05-07 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_user_login_loginuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
