# Generated by Django 4.0.4 on 2022-05-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
