# Generated by Django 4.0.4 on 2022-05-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=10)),
                ('product_image', models.ImageField(upload_to='home/img')),
                ('product_price', models.CharField(max_length=10)),
            ],
        ),
    ]
