# Generated by Django 4.0.4 on 2022-06-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_order_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='user',
        ),
    ]
