# Generated by Django 4.0.4 on 2022-05-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
