# Generated by Django 4.0.4 on 2022-06-03 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_username_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='username',
        ),
    ]
