# Generated by Django 4.0.4 on 2022-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gmail',
            field=models.DateTimeField(),
        ),
    ]
