# Generated by Django 4.0.4 on 2022-06-06 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_order_gmail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='gmail',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
