# Generated by Django 4.0.4 on 2022-05-10 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_user_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
