# Generated by Django 4.0.4 on 2022-06-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.ImageField(default='', max_length=30, upload_to=''),
        ),
    ]
