# Generated by Django 4.0.4 on 2022-05-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='customerservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_image', models.ImageField(upload_to='home/img')),
                ('cus_des', models.CharField(max_length=50)),
            ],
        ),
    ]
