# Generated by Django 4.0.4 on 2022-05-11 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_customerservice_cus_des'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='signupuser',
        ),
    ]
