# Generated by Django 4.0.4 on 2022-05-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_signupuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='signupuser',
            new_name='signup',
        ),
    ]
