# Generated by Django 4.0.4 on 2022-05-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_rename_signupuser_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customerservice',
        ),
    ]
