# Generated by Django 4.0.4 on 2022-06-07 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_order_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=models.FloatField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(default='', max_length=50),
        ),
    ]
