# Generated by Django 4.0.4 on 2022-06-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_order_pincode_alter_order_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.CharField(default='', max_length=30),
        ),
    ]
