# Generated by Django 4.0.4 on 2022-05-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_delete_customerservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(height_field=100, upload_to='home/img', width_field=100),
        ),
    ]
