# Generated by Django 4.0.4 on 2022-05-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=30)),
            ],
        ),
    ]
