# Generated by Django 4.0.4 on 2022-05-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='State',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='password',
            new_name='state',
        ),
    ]
