# Generated by Django 4.0.4 on 2022-05-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_state_order_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
