# Generated by Django 4.0.4 on 2022-06-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_order_number_alter_order_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_qty',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_qty',
            field=models.IntegerField(default=''),
        ),
    ]
