# Generated by Django 4.0.4 on 2022-05-27 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
