# Generated by Django 4.0.4 on 2022-05-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user_name',
            new_name='username',
        ),
    ]
