# Generated by Django 4.0.4 on 2022-05-27 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_user_name_signup_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='user_name',
        ),
    ]
