# Generated by Django 4.0.4 on 2022-05-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_rename_username_signup_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
