# Generated by Django 4.0.4 on 2022-05-27 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_signup_address_remove_signup_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='user_name',
            new_name='username',
        ),
    ]
